config/routes.rb
Rails.application.routes.draw do
  get 'posts/tagged/:tag' => 'posts#tag'
  get 'posts/pick_up' => 'posts#pick_up'
  post  'posts/pick_up_update' => 'posts#pick_up_update'
  resources :posts
  get '/' => 'posts#index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :taggings, :dependent => :destroy
  has_many :tags, through: :taggings
  mount_uploader :image_name, PostImageUploader
  has_rich_text :content

  validates :title, presence: true
  NUMBER_POST=7

  def save_posts(savepost_tags)
    current_tags = self.tags.pluck(:name) unless self.tags.nil?
    old_tags = current_tags - savepost_tags
    new_tags = savepost_tags - current_tags

    old_tags.each do |old_name|
      self.tags.delete Tag.find_by(name: old_name)
    end

    new_tags.each do |new_name|
      new_tag =  Tag.find_or_create_by(name: new_name)
      self.tags << new_tag
    end
  end

  def related_posts(q = NUMBER_POST)
    Post.includes(:tags).where(tags: {name: tags.pluck(:name)}).where.not(id:id).distinct.sample(q)
  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  authorize_resource
  before_action :set_post, only: [:show, :edit, :update, :destroy]



  # GET /posts
  # GET /posts.json
  def index
    # @posts = Post.page(params[:page]).per(PER).order(created_at: "DESC")
    @pickup_posts =  Post.where(pick_up: true)
    @q = Post.ransack(params[:q])
    @posts = @q.result.includes(:tags).page(params[:page]).per(PER).order(created_at: "DESC")
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @related_posts = @post.related_posts
  end

  def tag
    @tag = Tag.find_by(id: params[:tag])
    @posts = @tag.posts.page(params[:page]).per(PER).order(created_at: "DESC")
    @pickup_posts =  Post.where(pick_up: true)
  end

  def pick_up
    @posts=Post.all.order(created_at: "DESC")
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params.except(:tag_list))
    tag_list = post_params[:tag_list].split(/\s*,\s*/)
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: '投稿できました' }
        format.json { render :show, status: :created, location: @post }
        @post.save_posts(tag_list)
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    tag_list = post_params[:tag_list].split(/\s*,\s*/)
    respond_to do |format|
      if @post.update(title:post_params[:title],
        content:post_params[:content],
        image_name: post_params[:image_name])
        format.html { redirect_to @post, notice: '編集できませんでした' }
        format.json { render :show, status: :ok, location: @post }
        @post.save_posts(tag_list)
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def pick_up_update
    for i in Post.all.ids do
      @post=Post.find_by(id: i)
      @post.update(pick_up: params[:params][:pick_up][i.to_s])
    end
    redirect_to("/")
    # ①全部確認
    # render plain: params.inspect
    # ②特定値のみ確認
    # render plain: params[:params][:pick_up]["25"].inspect
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end



    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :image_name, :content, :tag_list)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title,"タイトル", class: "control-label" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :tag_list,"タグ（,区切りで入力してください）", class: "control-label" %>
    <%= form.text_field :tag_list, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :content, class: "control-label" %>
    <%= form.rich_text_area :content %>
  </div>

  <div class="field">
    <%= form.label :image_name,"サムネイル", class: "control-label" %>
    <%= form.file_field :image_name, accept: 'image/jpg,image/jpeg,image/png,image/gif', class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit :class => 'btn btn-dark', :value => '投稿する' %>
  </div>
<% end %>

app/views/posts/_form_pick_up.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-10 offset-sm-1">
      <h1>ピックアップする記事</h1>
      <%= form_with( local: true, url: posts_pick_up_update_path) do |form| %>
      <div class="field">
        <ul class="pick_up_scroll">
          <% @posts.each do |post| %>
          <li>
            <% if post.pick_up %>
            <%= form.check_box "params[pick_up][#{post.id}]", {checked: true},checked_value = "true",unchecked_value = "false" %>
            <%= post.title %>
            <% else %>
            <%= form.check_box "params[pick_up][#{post.id}]",{} ,checked_value="true", unchecked_value="false" %>
            <%= post.title %>
            <% end %>
          </li>
          <% end %>
        </ul>
      </div>
      <div class="actions">
        <%= form.submit :class => 'btn btn-dark'%>
      </div>
      <%end%>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<h1>編集する</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<% if @pickup_posts %>
<div id="carouselIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <% @pickup_posts.each_with_index do |pickup,i| %>
    <li data-target="#carouselIndicators" data-slide-to="<%="#{i}"%>" ></li>
    <% end %>
  </ol>
  <div class="carousel-inner">
    <% @pickup_posts.each do |pickup| %>
    <div class="carousel-item">
      <div class="carousel-wrap">
        <div class="slide-image">
          <%= link_to "/posts/#{pickup.id}" do %>
          <%= image_tag pickup.image_name.url %>
          <div class="image-title">
            <h3><%= pickup.title %></h3>
          </div>
          <% end %>
        </div>
        <div class="carousel-article-wrap">
          <div class="carousel-title-wrap">
            <%= link_to "/posts/#{pickup.id}" do %>
              <h3><%= pickup.title %></h3>
            <% end %>
          </div>
          <div class="carousel-content-wrap">
            <%= pickup.content %>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>
<% end %>


<div class="container">
  <div class="row">
    <div class="col-md-8 col-sm-12">
      <% @posts.each do |post| %>
        <div class="article-wrap">
          <div class="article">
            <div class="image-box">
              <%= link_to "/posts/#{post.id}" do %>
              <%= image_tag post.image_name.url %>
              <%end%>
            </div>
            <div class="body-box">
              <div class="article-body">
                <div class="inner">
                  <h3 class="article-title"><%=link_to post.title, "/posts/#{post.id}" %></h3>
                  <p><%= post.content %></p>
                </div>
                <div class="publish-time-wrap">
                  <p class="article-text"><%= simple_time(post[:created_at]) %></p>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>

    <div class="col-md-4">
      <div class="pickup">
        <h3>ピックアップ記事</h3>
        <div class="contents-wrap">
          <% @pickup_posts.each do |pickup| %>
            <%= link_to post_path(pickup) do %>
            <div class="content">
              <div class="content-image">
                <%= image_tag pickup.image_name.url %>
              </div>
              <div class="content-title">
                <h4><%= pickup.title %></h4>
              </div>
            </div>
            <%end%>
          <%end%>
        </div>
      </div>
    </div>
  </div>

  <div class="paginate-container">
    <%= paginate @posts %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-10 offset-sm-1">
      <h1>新規投稿</h1>
      
      <%= render 'form', post: @post %>
    </div>
  </div>
</div>

app/views/posts/pick_up.html.erb
<%= render 'form_pick_up'%>

app/views/posts/show.html.erb
<div class="container archive-wrap">
  <div class="row">
    <div class="col-md-10 offset-md-1 col-sm-11 offset-sm-1">
      <h1><%= @post.title %></h1>
      <div class="icon-tag">
        <%= icon('fas','tag') %>
        <% @post.tags.each do |tag|%>
          <div class="badge badge-primary tag-badge">
            <%= link_to tag.name, "/posts/tagged/#{tag.id}" %>
          </div>
        <%end%>
      </div>
      <div class="icon-publish">
        <span class="clock"><%= icon('far','clock')%></span><%=simple_time(@post.created_at) %>
      </div>
      <div class="content-wrap">
        <div class="thumb-container">
          <%= image_tag @post.image_name.url%>
        </div>
        <hr>
        <p><%= @post.content %></p>
      </div>
      <h3>関連記事</h3>
      <div class="related_post_wrap">
        <% @related_posts.each do |related_post| %>
        <div class="related_post">
          <%= link_to post_path(related_post) do %>
          <div class="related_post_image">
            <%= image_tag related_post.image_name.url%>
          </div>
          <div class="related_post_title">
            <h4><%= related_post.title %></h4>
          </div>
          <% end %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/tag.html.erb
<% if @pickup_posts %>
<div id="carouselIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <% @pickup_posts.each_with_index do |pickup,i| %>
    <li data-target="#carouselIndicators" data-slide-to="<%="#{i}"%>" ></li>
    <% end %>
  </ol>
  <div class="carousel-inner">
    <% @pickup_posts.each do |pickup| %>
    <div class="carousel-item">
      <div class="carousel-wrap">
        <div class="slide-image">
          <%= link_to "/posts/#{pickup.id}" do %>
          <%= image_tag pickup.image_name.url %>
          <div class="image-title">
            <h3><%= pickup.title %></h3>
          </div>
          <% end %>
        </div>
        <div class="carousel-article-wrap">
          <div class="carousel-title-wrap">
            <%= link_to "/posts/#{pickup.id}" do %>
              <h3><%= pickup.title %></h3>
            <% end %>
          </div>
          <div class="carousel-content-wrap">
            <%= pickup.content %>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>
<% end %>


<div class="container">
  <div class="row">
    <div class="col-md-8 col-sm-12">
      <h2><span class="badge badge-primary"><%= @tag.name %></span> タグがついた投稿</h2>
      <% @posts.each do |post| %>
        <div class="article-wrap">
          <div class="article">
            <div class="image-box">
              <%= link_to "/posts/#{post.id}" do %>
              <%= image_tag post.image_name.url %>
              <%end%>
            </div>
            <div class="body-box">
              <div class="article-body">
                <div class="inner">
                  <h3 class="article-title"><%=link_to post.title, "/posts/#{post.id}" %></h3>
                  <p><%= post.content %></p>
                </div>
                <div class="publish-time-wrap">
                  <p class="article-text"><%= simple_time(post[:created_at]) %></p>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>

    <div class="col-md-4">
      <div class="pickup">
        <h3>ピックアップ記事</h3>
        <div class="contents-wrap">
          <% @pickup_posts.each do |pickup| %>
            <%= link_to post_path(pickup) do %>
            <div class="content">
              <div class="content-image">
                <%= image_tag pickup.image_name.url %>
              </div>
              <div class="content-title">
                <h4><%= pickup.title %></h4>
              </div>
            </div>
            <%end%>
          <%end%>
        </div>
      </div>
    </div>
  </div>

  <div class="paginate-container">
    <%= paginate @posts %>
  </div>
</div>